import type { Metadata } from 'next';
import './globals.css';
import HandleMenu from './components/handleMenu'
import { GoogleAnalytics } from '@next/third-parties/google'

export const metadata: Metadata = {
  title: 'Home — Portfolio',
  description: 'Generated by KH',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="pl">
      <head>
      </head>
      <body>
        <HandleMenu />
        {children}
        <GoogleAnalytics gaId="G-QKLH1Y70TR" />
      </body>
    </html>
  );
}