import type { Metadata } from 'next';
import './globals.css';
import HandleMenu from './components/handleMenu'


export const metadata: Metadata = {
  title: 'Home — Portfolio',
  description: 'Generated by KH',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <HandleMenu />
        {children}
      </body>
    </html>
  );
}